const PORTFOLIO_DATA = {
  meta: {
    name: "Siddhesh Desai",
    title: "AI & Data Engineer",
    tagline: "I build scalable data pipelines and multi-agent AI systems.",
    email: "siddheshdesai777@gmail.com",
    linkedin: "https://linkedin.com/in/thesiddheshdesai",
    github: "https://github.com/siddhesh-desai",
    twitter: "https://twitter.com/siddheshdesai_",
    resume: "assets/resume.pdf",
  },

  about: [
    'I\'m an engineer who specializes in building data infrastructure and AI systems that work at scale. Currently at <a href="https://www.data-axle.com/" target="_blank" rel="noopener">Data Axle</a>, I architect ETL pipelines processing millions of records on AWS and build synthetic data frameworks that unblock entire engineering teams.',
    'Previously, I\'ve designed multi-agent AI systems at <a href="#experience">Qest</a>, fine-tuned LLMs for clients like Apple at <a href="#experience">Turing</a>, and built NLP pipelines for customer intelligence at <a href="#experience">Coinbase</a>. I\'ve led a 6-member team to win 10+ hackathons including back-to-back Smart India Hackathon (2022 & 2023) and Citi Bank Hackathon (2024 & 2025).',
    'My focus is on the intersection of data engineering and AI - making models work in production, not just in notebooks. I care about clean pipelines, reliable inference, and systems that ship.',
  ],

  experience: [
    {
      role: "AI & Data Engineer",
      company: "Data Axle",
      date: "May 2025 - Present",
      image: null,
      link: null,
      bullets: [
        "Developed scalable ETL/ELT pipelines on AWS with Apache Spark, integrating MDM processes for high-volume datasets",
        "Led tech design of org-wide synthetic test data platform (team of 4) as Higher Gear initiative, generating millions of realistic records with cross-referential integrity",
        "Engineered file-upload mimic feature that analyzes datasets to replicate column structures and data patterns, accelerating test data onboarding for QA teams",
        "Designed Agentic AI Data Dictionary Generator with Human-in-the-Loop validation, automating metadata for 100s of tables with 1000s of columns, powering Text-to-SQL chatbot",
        "Reduced Git integration bottlenecks by 75% in DAG task via shallow clone strategy, cutting execution from ~10 minutes to under 2 minutes",
        "Automated cross-environment Superset dashboard transfers via GitHub Actions, eliminating manual migration effort",
        "Deployed Keycloak as unified SSO solution, building org-wide authentication framework serving customers, clients, and employees",
      ],
      tags: ["Python", "PySpark", "AWS", "Docker", "Airflow", "PostgreSQL", "Keycloak", "Superset"],
    },
    {
      role: "Generative AI Engineer Intern",
      company: "Qest",
      date: "Mar 2025 - May 2025",
      image: null,
      link: null,
      bullets: [
        "Part of founding AI team; architected core backend framework for multi-agent AI systems with MCP connections, internal API tool integration, and efficient context management, leading to 30% reduction in LLM inference costs",
        "Built scalable FastAPI-based public interface for agent deployment, enabling seamless orchestration and reducing deployment time significantly",
      ],
      tags: ["LangGraph", "FastAPI", "LLMs", "Multi-Agent", "MCP", "Python"],
    },
    {
      role: "Data Analyst Intern",
      company: "Turing",
      date: "Aug 2024 - Jan 2025",
      image: null,
      link: null,
      bullets: [
        "Improved Apple's Large Language Model contextual accuracy by 25% by fine-tuning for Data Science and Machine Learning tasks using LoRA, QLoRA, SFT, RLHF, and NLP techniques",
        "Identified and mitigated critical failure points in language understanding, reducing hallucinations and improving production model performance",
      ],
      tags: ["LLMs", "RLHF", "NLP", "Python", "Fine-Tuning"],
    },
    {
      role: "Machine Learning Intern",
      company: "Coinbase",
      date: "May 2024 - Aug 2024",
      image: null,
      link: null,
      bullets: [
        "Designated owner of Project Insights: designed and developed end-to-end LLM-powered batch pipeline to extract actionable insights from Customer Chat and HR textual data, increasing decision-making accuracy by 50%",
        "Leveraged NLP and embedding techniques to extract key topics, cluster similar topics, and categorize them, enhancing data organization and retrieval efficiency",
        "Built interactive Looker dashboard for stakeholders to explore and derive insights from processed data, enabling self-serve analytics across teams",
      ],
      tags: ["LLMs", "NLP", "Python", "Machine Learning", "Airflow", "Looker"],
    },
  ],

  leadership: [
    {
      role: "Research Ambassador",
      org: "Springer Nature",
      date: "2024 - Present",
      description: "Supporting researchers through publication strategies, contributing to the global research community.",
    },
    {
      role: "President",
      org: "Abhivriddhi - Student Training & Development, VIT Pune",
      date: "2023 - 2024",
      description: "Led 140+ members, driving 200% better impact. Managed large-scale events impacting 1000+ students.",
    },
    {
      role: "Jury Member",
      org: "Internal Smart India Hackathon 2025, VIT Pune",
      date: "2025",
      description: "Evaluated and mentored student innovation projects as judge.",
    },
    {
      role: "Teaching Assistant",
      org: "VIT Pune",
      date: "2023 - 2024",
      description: "Taught C & C++ to 70+ students through 10 tutorials, improving programming proficiency.",
    },
  ],

  featuredProjects: [
    {
      title: "citiWise - AI Powered Family Finance App",
      description: "Full-stack finance web app with real-time bank account access and citiGPT assistant leveraging RAG, AI agents, and open-source models for personalized financial guidance. 1st place at Citi Bank Hackathon.",
      tags: ["Node.js", "Express", "MongoDB", "LangChain", "RAG", "Fintech"],
      github: "https://github.com/siddhesh-desai/citiGPT",
      badge: "Citi Bank Hackathon Winner",
      image: null,
    },
    {
      title: "CitiChain - Blockchain Banking Platform",
      description: "Next-gen blockchain banking platform unifying traditional finance and DeFi. Engineered OneKYC with Zero-Knowledge Proofs, INR-pegged stablecoin (RupeeX), consent ledger via Merkle Trees & IPFS, and CitiGPT AI assistant. Back-to-back Citi Bank Hackathon 2025 winner.",
      tags: ["Node.js", "React", "Solidity", "Web3", "Zero-Knowledge Proofs"],
      github: "https://github.com/siddhesh-desai/citiChain",
      badge: "Citi Bank Hackathon 2025 Winner",
      image: null,
    },
    {
      title: "LadleVision",
      description: "Computer Vision system for real-time hot metal, steel ladle, and scrap pot tracking at Vizag Steel Plant with 95% detection accuracy. YOLO-based ladle detection with OCR, cross-camera tracking, and analytics server. Full offline portal deployed at plant.",
      tags: ["Computer Vision", "YOLO", "Python", "Node.js", "IoT"],
      github: "https://github.com/siddhesh-desai/LadleVision",
      badge: "SIH 2023 Winner",
      image: null,
    },
    {
      title: "SlideAI",
      description: "AI Presentation maker that helps students build project presentations in seconds with a few prompts. 130+ GitHub stars and published patent showcasing its contributions.",
      tags: ["JavaScript", "AppScript", "OpenAI", "LLM"],
      github: "https://github.com/siddhesh-desai/SlideAI",
      badge: "130+ Stars · Patent",
      image: null,
    },
  ],

  archive: [
    { year: "2025", title: "Synthetic Test Data Platform", tags: ["Python", "React", "Django", "PostgreSQL"], madeAt: "Data Axle", github: null, demo: null, badge: "Production" },
    { year: "2025", title: "Agentic AI Data Dictionary Generator", tags: ["Python", "Strands Agents", "AWS Bedrock"], madeAt: "Data Axle", github: null, demo: null, badge: "Production" },
    { year: "2025", title: "CitiChain - Blockchain Banking", tags: ["Node.js", "React", "Solidity", "Web3"], madeAt: null, github: "https://github.com/siddhesh-desai/citiChain", demo: null, badge: "Citi Hackathon Winner" },
    { year: "2025", title: "Multi-Agent AI Framework", tags: ["LangGraph", "FastAPI", "MCP"], madeAt: "Qest", github: null, demo: null, badge: null },
    { year: "2025", title: "TBO EventEase", tags: ["Python", "FastAPI", "LangChain"], madeAt: null, github: "https://github.com/siddhesh-desai/tboease-api", demo: null, badge: "TBO Top 5" },
    { year: "2025", title: "RFPInsight", tags: ["Python", "LangChain", "Pinecone"], madeAt: null, github: "https://github.com/siddhesh-desai/rfp-agent", demo: null, badge: "ConsultAdd Top 5" },
    { year: "2024", title: "citiWise / citiGPT", tags: ["Node.js", "LangChain", "RAG", "Fintech"], madeAt: null, github: "https://github.com/siddhesh-desai/citiGPT", demo: "https://citiwise.vercel.app/", badge: "Citi Hackathon Winner" },
    { year: "2024", title: "Project Insights - LLM Pipeline", tags: ["Python", "LLM", "NLP", "Airflow"], madeAt: "Coinbase", github: null, demo: null, badge: null },
    { year: "2024", title: "LegalAIBot", tags: ["Python", "LangChain", "Pinecone", "Docling"], madeAt: null, github: "https://github.com/siddhesh-desai/LegalAIBot", demo: null, badge: null },
    { year: "2023", title: "LadleVision", tags: ["Computer Vision", "YOLO", "Python", "Node.js"], madeAt: null, github: "https://github.com/siddhesh-desai/LadleVision", demo: "https://ladlevision.onrender.com/", badge: "SIH Winner" },
    { year: "2023", title: "SlideAI", tags: ["JavaScript", "AppScript", "OpenAI"], madeAt: null, github: "https://github.com/siddhesh-desai/SlideAI", demo: null, badge: "130+ Stars · Patent" },
    { year: "2023", title: "Vote Bharat", tags: ["Flutter", "Firebase", "Firestore"], madeAt: null, github: "https://github.com/siddhesh-desai/vote-bharat", demo: null, badge: "Electhon Top 10" },
    { year: "2023", title: "WorkerConnect", tags: ["React", "Django", "PostgreSQL"], madeAt: null, github: "https://github.com/siddhesh-desai/Worker-Connect", demo: null, badge: null },
    { year: "2022", title: "SIH 2022 Project", tags: ["Python", "ML"], madeAt: null, github: null, demo: null, badge: "SIH Winner" },
  ],

  achievements: [
    { title: "Data Axle Nova Award (Badge of Honour)", description: "Awarded by CTO & MD of Data Axle India within first 3 months of joining, in recognition of exceptional early impact and initiative.", year: "2025", link: null, image: null },
    { title: "Patent & Research Paper", description: "Published patent and research paper, presented findings at two international conferences.", year: "2024", link: "https://drive.google.com/open?id=134TAWkx0hYKZRMsyOF606DXU9U_ZzIWh", image: null },
    { title: "Led 6-member team to 10+ Hackathon Wins", description: "Back-to-back wins at Smart India Hackathon 2022 & 2023, Citi Bank Hackathon 2024 & 2025, Ada Lovelace Hackathon, AICTE IDE Bootcamp, Unscript Hackathon, and more.", year: "2022 - 2025", link: null, image: null },
    { title: "Citi Bank Hackathon 2024 - Winners", description: "Built citiWise / citiGPT, AI financial assistant. Winning project among top engineering teams.", year: "2024", link: null, image: null },
    { title: "Citi Bank Hackathon 2025 - Winners", description: "Built CitiChain, blockchain banking platform. Back-to-back win.", year: "2025", link: null, image: null },
    { title: "Smart India Hackathon 2023 - Winners", description: "Built LadleVision for steel plant automation. National-level, Government of India.", year: "2023", link: null, image: null },
    { title: "Smart India Hackathon 2022 - Winners", description: "Won the national-level SIH, competing against thousands of teams across India.", year: "2022", link: null, image: null },
    { title: "ConsultAdd Hackathon - Top 5 Finalist", description: "RFPInsight, AI-powered solution automating legal, compliance, and risk analysis of government RFPs.", year: "2024", link: null, image: null },
    { title: "TBO Hackathon - Top 5 Finalist", description: "EventEase, AI-driven corporate event planning platform with multi-agent itinerary generation.", year: "2024", link: null, image: null },
    { title: "Electhon - Top 10 Finalist", description: "Vote Bharat, voter engagement mobile app. Organized by Election Commission of India & Government of Karnataka.", year: "2023", link: null, image: null },
    { title: "Unscript Rookies Hackathon - Winners", description: "Won with an innovative solution among hundreds of competing teams.", year: "2022", link: null, image: null },
    { title: "Coding Ninjas Founders Meet - Top 100", description: "Recognized among top 100 coders in the national challenge.", year: "2023", link: null, image: null },
    { title: "National Entrepreneurship Olympiad - Rank 22", description: "Secured nationally in competitive entrepreneurship assessment.", year: "2021", link: null, image: null },
    { title: "Keynote Speaker", description: "Invited to guide engineering students on hackathons at KIT, VIT, and other colleges.", year: "2024", link: null, image: null },
  ],

  neuralNet: {
    sections: ["about", "experience", "projects", "achievements"],
  },
};
